FROM python:3.9-slim
WORKDIR /app
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app/ ./app/
COPY models/ ./models/
EXPOSE 5000
ENV MODEL_PATH=models/model.pkl
CMD ["python", "app/app.py"]